// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.4 by WSRD Tencent.
// Generated from `LogReport.jce'
// **********************************************************************

package TRom.log;

public final class GetTicketRsp extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "TRom.GetTicketRsp";
    }

    public String fullClassName()
    {
        return "TRom.GetTicketRsp";
    }

    public String sTicket = "";

    public String getSTicket()
    {
        return sTicket;
    }

    public void  setSTicket(String sTicket)
    {
        this.sTicket = sTicket;
    }

    public GetTicketRsp()
    {
    }

    public GetTicketRsp(String sTicket)
    {
        this.sTicket = sTicket;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetTicketRsp t = (GetTicketRsp) o;
        return (
            com.qq.taf.jce.JceUtil.equals(sTicket, t.sTicket) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != sTicket)
        {
            _os.write(sTicket, 0);
        }
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.sTicket =  _is.readString(0, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(sTicket, "sTicket");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(sTicket, false);
    }

}

