// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.4 by WSRD Tencent.
// Generated from `KobeshyTest.jce'
// **********************************************************************

package TRom;

public final class GetKobeRsp extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "TRom.GetKobeRsp";
    }

    public String fullClassName()
    {
        return "TRom.GetKobeRsp";
    }

    public int iRet = 0;

    public String sInfos = "";

    public TRom.KobeInfo stKoby = null;

    public java.util.ArrayList<TRom.KobeInfo> vKobyList = null;

    public java.util.Map<Integer, TRom.KobeInfo> mKobys = null;

    public int getIRet()
    {
        return iRet;
    }

    public void  setIRet(int iRet)
    {
        this.iRet = iRet;
    }

    public String getSInfos()
    {
        return sInfos;
    }

    public void  setSInfos(String sInfos)
    {
        this.sInfos = sInfos;
    }

    public TRom.KobeInfo getStKoby()
    {
        return stKoby;
    }

    public void  setStKoby(TRom.KobeInfo stKoby)
    {
        this.stKoby = stKoby;
    }

    public java.util.ArrayList<TRom.KobeInfo> getVKobyList()
    {
        return vKobyList;
    }

    public void  setVKobyList(java.util.ArrayList<TRom.KobeInfo> vKobyList)
    {
        this.vKobyList = vKobyList;
    }

    public java.util.Map<Integer, TRom.KobeInfo> getMKobys()
    {
        return mKobys;
    }

    public void  setMKobys(java.util.Map<Integer, TRom.KobeInfo> mKobys)
    {
        this.mKobys = mKobys;
    }

    public GetKobeRsp()
    {
    }

    public GetKobeRsp(int iRet, String sInfos, TRom.KobeInfo stKoby, java.util.ArrayList<TRom.KobeInfo> vKobyList, java.util.Map<Integer, TRom.KobeInfo> mKobys)
    {
        this.iRet = iRet;
        this.sInfos = sInfos;
        this.stKoby = stKoby;
        this.vKobyList = vKobyList;
        this.mKobys = mKobys;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetKobeRsp t = (GetKobeRsp) o;
        return (
            com.qq.taf.jce.JceUtil.equals(iRet, t.iRet) && 
            com.qq.taf.jce.JceUtil.equals(sInfos, t.sInfos) && 
            com.qq.taf.jce.JceUtil.equals(stKoby, t.stKoby) && 
            com.qq.taf.jce.JceUtil.equals(vKobyList, t.vKobyList) && 
            com.qq.taf.jce.JceUtil.equals(mKobys, t.mKobys) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(iRet, 0);
        if (null != sInfos)
        {
            _os.write(sInfos, 1);
        }
        if (null != stKoby)
        {
            _os.write(stKoby, 2);
        }
        if (null != vKobyList)
        {
            _os.write(vKobyList, 3);
        }
        if (null != mKobys)
        {
            _os.write(mKobys, 4);
        }
    }

    static TRom.KobeInfo cache_stKoby;
    static java.util.ArrayList<TRom.KobeInfo> cache_vKobyList;
    static java.util.Map<Integer, TRom.KobeInfo> cache_mKobys;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.iRet = (int) _is.read(iRet, 0, false);
        this.sInfos =  _is.readString(1, false);
        if(null == cache_stKoby)
        {
            cache_stKoby = new TRom.KobeInfo();
        }
        this.stKoby = (TRom.KobeInfo) _is.read(cache_stKoby, 2, false);
        if(null == cache_vKobyList)
        {
            cache_vKobyList = new java.util.ArrayList<TRom.KobeInfo>();
            TRom.KobeInfo __var_4 = new TRom.KobeInfo();
            ((java.util.ArrayList<TRom.KobeInfo>)cache_vKobyList).add(__var_4);
        }
        this.vKobyList = (java.util.ArrayList<TRom.KobeInfo>) _is.read(cache_vKobyList, 3, false);
        if(null == cache_mKobys)
        {
            cache_mKobys = new java.util.HashMap<Integer, TRom.KobeInfo>();
            Integer __var_5 = 0;
            TRom.KobeInfo __var_6 = new TRom.KobeInfo();
            cache_mKobys.put(__var_5, __var_6);
        }
        this.mKobys = (java.util.Map<Integer, TRom.KobeInfo>) _is.read(cache_mKobys, 4, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(iRet, "iRet");
        _ds.display(sInfos, "sInfos");
        _ds.display(stKoby, "stKoby");
        _ds.display(vKobyList, "vKobyList");
        _ds.display(mKobys, "mKobys");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(iRet, true);
        _ds.displaySimple(sInfos, true);
        _ds.displaySimple(stKoby, true);
        _ds.displaySimple(vKobyList, true);
        _ds.displaySimple(mKobys, false);
    }

}

