// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.4 by WSRD Tencent.
// Generated from `KobeshyTest.jce'
// **********************************************************************

package TRom;

public final class GetKobeReq extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "TRom.GetKobeReq";
    }

    public String fullClassName()
    {
        return "TRom.GetKobeReq";
    }

    public int iId = 0;

    public String sName = "";

    public int getIId()
    {
        return iId;
    }

    public void  setIId(int iId)
    {
        this.iId = iId;
    }

    public String getSName()
    {
        return sName;
    }

    public void  setSName(String sName)
    {
        this.sName = sName;
    }

    public GetKobeReq()
    {
    }

    public GetKobeReq(int iId, String sName)
    {
        this.iId = iId;
        this.sName = sName;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetKobeReq t = (GetKobeReq) o;
        return (
            com.qq.taf.jce.JceUtil.equals(iId, t.iId) && 
            com.qq.taf.jce.JceUtil.equals(sName, t.sName) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(iId, 0);
        _os.write(sName, 1);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.iId = (int) _is.read(iId, 0, true);
        this.sName =  _is.readString(1, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(iId, "iId");
        _ds.display(sName, "sName");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(iId, true);
        _ds.displaySimple(sName, false);
    }

}

