// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.1.1.2 by WSRD Tencent.
// Generated from `LoginQ.jce'
// **********************************************************************

package TRom;

public final class EIPType implements java.io.Serializable
{
    private static EIPType[] __values = new EIPType[3];
    private int __value;
    private String __T = new String();

    public static final int _WUPPROXY = 1;
    public static final EIPType WUPPROXY = new EIPType(0,_WUPPROXY,"WUPPROXY");
    public static final int _PUSHSOCKET = 2;
    public static final EIPType PUSHSOCKET = new EIPType(1,_PUSHSOCKET,"PUSHSOCKET");
    public static final int _WUPSOCKET = 3;
    public static final EIPType WUPSOCKET = new EIPType(2,_WUPSOCKET,"WUPSOCKET");

    public static EIPType convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        return null;
    }

    public static EIPType convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private EIPType(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
