// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.1.1.2 by WSRD Tencent.
// Generated from `LoginQ.jce'
// **********************************************************************

package TRom;

public final class LoginRsp extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "TRom.LoginRsp";
    }

    public String fullClassName()
    {
        return "TRom.LoginRsp";
    }

    public byte [] vGUID = null;

    public byte [] getVGUID()
    {
        return vGUID;
    }

    public void  setVGUID(byte [] vGUID)
    {
        this.vGUID = vGUID;
    }

    public LoginRsp()
    {
    }

    public LoginRsp(byte [] vGUID)
    {
        this.vGUID = vGUID;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        LoginRsp t = (LoginRsp) o;
        return (
            com.qq.taf.jce.JceUtil.equals(vGUID, t.vGUID) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != vGUID)
        {
            _os.write(vGUID, 0);
        }
    }

    static byte [] cache_vGUID;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        if(null == cache_vGUID)
        {
            cache_vGUID = (byte[]) new byte[1];
            byte __var_1 = 0;
            ((byte[])cache_vGUID)[0] = __var_1;
        }
        this.vGUID = (byte []) _is.read(cache_vGUID, 0, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(vGUID, "vGUID");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(vGUID, false);
    }

}

