// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `Security.jce'
// **********************************************************************

package TRom;

public final class SecPublicKeyRsp extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "TRom.SecPublicKeyRsp";
    }

    public String fullClassName()
    {
        return "TRom.SecPublicKeyRsp";
    }

    public String sPublicKey = "";

    public int iPubKeyVer = 0;

    public byte [] vtMd5Signature = null;

    public String getSPublicKey()
    {
        return sPublicKey;
    }

    public void  setSPublicKey(String sPublicKey)
    {
        this.sPublicKey = sPublicKey;
    }

    public int getIPubKeyVer()
    {
        return iPubKeyVer;
    }

    public void  setIPubKeyVer(int iPubKeyVer)
    {
        this.iPubKeyVer = iPubKeyVer;
    }

    public byte [] getVtMd5Signature()
    {
        return vtMd5Signature;
    }

    public void  setVtMd5Signature(byte [] vtMd5Signature)
    {
        this.vtMd5Signature = vtMd5Signature;
    }

    public SecPublicKeyRsp()
    {
        setSPublicKey(sPublicKey);
        setIPubKeyVer(iPubKeyVer);
        setVtMd5Signature(vtMd5Signature);
    }

    public SecPublicKeyRsp(String sPublicKey, int iPubKeyVer, byte [] vtMd5Signature)
    {
        setSPublicKey(sPublicKey);
        setIPubKeyVer(iPubKeyVer);
        setVtMd5Signature(vtMd5Signature);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        SecPublicKeyRsp t = (SecPublicKeyRsp) o;
        return (
            com.qq.taf.jce.JceUtil.equals(sPublicKey, t.sPublicKey) && 
            com.qq.taf.jce.JceUtil.equals(iPubKeyVer, t.iPubKeyVer) && 
            com.qq.taf.jce.JceUtil.equals(vtMd5Signature, t.vtMd5Signature) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(sPublicKey, 1);
        _os.write(iPubKeyVer, 2);
        _os.write(vtMd5Signature, 3);
    }

    static byte [] cache_vtMd5Signature;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setSPublicKey( _is.readString(1, true));

        setIPubKeyVer((int) _is.read(iPubKeyVer, 2, true));

        if(null == cache_vtMd5Signature)
        {
            cache_vtMd5Signature = (byte[]) new byte[1];
            byte __var_1 = 0;
            ((byte[])cache_vtMd5Signature)[0] = __var_1;
        }
        setVtMd5Signature((byte []) _is.read(cache_vtMd5Signature, 3, true));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(sPublicKey, "sPublicKey");
        _ds.display(iPubKeyVer, "iPubKeyVer");
        _ds.display(vtMd5Signature, "vtMd5Signature");
    }

}

