// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `Security.jce'
// **********************************************************************

package TRom;

public final class SecPublicKeyReq extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "TRom.SecPublicKeyReq";
    }

    public String fullClassName()
    {
        return "TRom.SecPublicKeyReq";
    }

    public TRom.RomBaseInfo stRomBaseInfo = null;

    public String sApp = "";

    public int iRootPubKeyVer = 1;

    public TRom.RomBaseInfo getStRomBaseInfo()
    {
        return stRomBaseInfo;
    }

    public void  setStRomBaseInfo(TRom.RomBaseInfo stRomBaseInfo)
    {
        this.stRomBaseInfo = stRomBaseInfo;
    }

    public String getSApp()
    {
        return sApp;
    }

    public void  setSApp(String sApp)
    {
        this.sApp = sApp;
    }

    public int getIRootPubKeyVer()
    {
        return iRootPubKeyVer;
    }

    public void  setIRootPubKeyVer(int iRootPubKeyVer)
    {
        this.iRootPubKeyVer = iRootPubKeyVer;
    }

    public SecPublicKeyReq()
    {
        setStRomBaseInfo(stRomBaseInfo);
        setSApp(sApp);
        setIRootPubKeyVer(iRootPubKeyVer);
    }

    public SecPublicKeyReq(TRom.RomBaseInfo stRomBaseInfo, String sApp, int iRootPubKeyVer)
    {
        setStRomBaseInfo(stRomBaseInfo);
        setSApp(sApp);
        setIRootPubKeyVer(iRootPubKeyVer);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        SecPublicKeyReq t = (SecPublicKeyReq) o;
        return (
            com.qq.taf.jce.JceUtil.equals(stRomBaseInfo, t.stRomBaseInfo) && 
            com.qq.taf.jce.JceUtil.equals(sApp, t.sApp) && 
            com.qq.taf.jce.JceUtil.equals(iRootPubKeyVer, t.iRootPubKeyVer) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != stRomBaseInfo)
        {
            _os.write(stRomBaseInfo, 0);
        }
        _os.write(sApp, 1);
        _os.write(iRootPubKeyVer, 2);
    }

    static TRom.RomBaseInfo cache_stRomBaseInfo;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        if(null == cache_stRomBaseInfo)
        {
            cache_stRomBaseInfo = new TRom.RomBaseInfo();
        }
        setStRomBaseInfo((TRom.RomBaseInfo) _is.read(cache_stRomBaseInfo, 0, false));

        setSApp( _is.readString(1, true));

        setIRootPubKeyVer((int) _is.read(iRootPubKeyVer, 2, true));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(stRomBaseInfo, "stRomBaseInfo");
        _ds.display(sApp, "sApp");
        _ds.display(iRootPubKeyVer, "iRootPubKeyVer");
    }

}

