// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `Security.jce'
// **********************************************************************

package TRom;

public final class SecSessionReq extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "TRom.SecSessionReq";
    }

    public String fullClassName()
    {
        return "TRom.SecSessionReq";
    }

    public TRom.RomBaseInfo stRomBaseInfo = null;

    public String sApp = "";

    public byte [] vtGuid = null;

    public int iAppPubKeyVer = 1;

    public byte [] vtEncryptedActiveKey = null;

    public TRom.RomBaseInfo getStRomBaseInfo()
    {
        return stRomBaseInfo;
    }

    public void  setStRomBaseInfo(TRom.RomBaseInfo stRomBaseInfo)
    {
        this.stRomBaseInfo = stRomBaseInfo;
    }

    public String getSApp()
    {
        return sApp;
    }

    public void  setSApp(String sApp)
    {
        this.sApp = sApp;
    }

    public byte [] getVtGuid()
    {
        return vtGuid;
    }

    public void  setVtGuid(byte [] vtGuid)
    {
        this.vtGuid = vtGuid;
    }

    public int getIAppPubKeyVer()
    {
        return iAppPubKeyVer;
    }

    public void  setIAppPubKeyVer(int iAppPubKeyVer)
    {
        this.iAppPubKeyVer = iAppPubKeyVer;
    }

    public byte [] getVtEncryptedActiveKey()
    {
        return vtEncryptedActiveKey;
    }

    public void  setVtEncryptedActiveKey(byte [] vtEncryptedActiveKey)
    {
        this.vtEncryptedActiveKey = vtEncryptedActiveKey;
    }

    public SecSessionReq()
    {
        setStRomBaseInfo(stRomBaseInfo);
        setSApp(sApp);
        setVtGuid(vtGuid);
        setIAppPubKeyVer(iAppPubKeyVer);
        setVtEncryptedActiveKey(vtEncryptedActiveKey);
    }

    public SecSessionReq(TRom.RomBaseInfo stRomBaseInfo, String sApp, byte [] vtGuid, int iAppPubKeyVer, byte [] vtEncryptedActiveKey)
    {
        setStRomBaseInfo(stRomBaseInfo);
        setSApp(sApp);
        setVtGuid(vtGuid);
        setIAppPubKeyVer(iAppPubKeyVer);
        setVtEncryptedActiveKey(vtEncryptedActiveKey);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        SecSessionReq t = (SecSessionReq) o;
        return (
            com.qq.taf.jce.JceUtil.equals(stRomBaseInfo, t.stRomBaseInfo) && 
            com.qq.taf.jce.JceUtil.equals(sApp, t.sApp) && 
            com.qq.taf.jce.JceUtil.equals(vtGuid, t.vtGuid) && 
            com.qq.taf.jce.JceUtil.equals(iAppPubKeyVer, t.iAppPubKeyVer) && 
            com.qq.taf.jce.JceUtil.equals(vtEncryptedActiveKey, t.vtEncryptedActiveKey) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != stRomBaseInfo)
        {
            _os.write(stRomBaseInfo, 0);
        }
        _os.write(sApp, 1);
        _os.write(vtGuid, 2);
        _os.write(iAppPubKeyVer, 3);
        _os.write(vtEncryptedActiveKey, 4);
    }

    static TRom.RomBaseInfo cache_stRomBaseInfo;
    static byte [] cache_vtGuid;
    static byte [] cache_vtEncryptedActiveKey;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        if(null == cache_stRomBaseInfo)
        {
            cache_stRomBaseInfo = new TRom.RomBaseInfo();
        }
        setStRomBaseInfo((TRom.RomBaseInfo) _is.read(cache_stRomBaseInfo, 0, false));

        setSApp( _is.readString(1, true));

        if(null == cache_vtGuid)
        {
            cache_vtGuid = (byte[]) new byte[1];
            byte __var_2 = 0;
            ((byte[])cache_vtGuid)[0] = __var_2;
        }
        setVtGuid((byte []) _is.read(cache_vtGuid, 2, true));

        setIAppPubKeyVer((int) _is.read(iAppPubKeyVer, 3, true));

        if(null == cache_vtEncryptedActiveKey)
        {
            cache_vtEncryptedActiveKey = (byte[]) new byte[1];
            byte __var_3 = 0;
            ((byte[])cache_vtEncryptedActiveKey)[0] = __var_3;
        }
        setVtEncryptedActiveKey((byte []) _is.read(cache_vtEncryptedActiveKey, 4, true));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(stRomBaseInfo, "stRomBaseInfo");
        _ds.display(sApp, "sApp");
        _ds.display(vtGuid, "vtGuid");
        _ds.display(iAppPubKeyVer, "iAppPubKeyVer");
        _ds.display(vtEncryptedActiveKey, "vtEncryptedActiveKey");
    }

}

