// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `Security.jce'
// **********************************************************************

package TRom;

public final class SecSessionRsp extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "TRom.SecSessionRsp";
    }

    public String fullClassName()
    {
        return "TRom.SecSessionRsp";
    }

    public String sSessionId = "";

    public String getSSessionId()
    {
        return sSessionId;
    }

    public void  setSSessionId(String sSessionId)
    {
        this.sSessionId = sSessionId;
    }

    public SecSessionRsp()
    {
        setSSessionId(sSessionId);
    }

    public SecSessionRsp(String sSessionId)
    {
        setSSessionId(sSessionId);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        SecSessionRsp t = (SecSessionRsp) o;
        return (
            com.qq.taf.jce.JceUtil.equals(sSessionId, t.sSessionId) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != sSessionId)
        {
            _os.write(sSessionId, 1);
        }
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setSSessionId( _is.readString(1, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(sSessionId, "sSessionId");
    }

}

