// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `Security.jce'
// **********************************************************************

package TRom;

public final class Securty_RetCode implements java.io.Serializable
{
    private static Securty_RetCode[] __values = new Securty_RetCode[8];
    private int __value;
    private String __T = new String();

    public static final int _SEC_RC_OK = 0;
    public static final Securty_RetCode SEC_RC_OK = new Securty_RetCode(0,_SEC_RC_OK,"SEC_RC_OK");
    public static final int _SEC_RC_INVALID_APP = -1;
    public static final Securty_RetCode SEC_RC_INVALID_APP = new Securty_RetCode(1,_SEC_RC_INVALID_APP,"SEC_RC_INVALID_APP");
    public static final int _SEC_RC_INVALID_SESSIONID = -2;
    public static final Securty_RetCode SEC_RC_INVALID_SESSIONID = new Securty_RetCode(2,_SEC_RC_INVALID_SESSIONID,"SEC_RC_INVALID_SESSIONID");
    public static final int _SEC_RC_ROOT_PUBKEY_EXPIRED = -3;
    public static final Securty_RetCode SEC_RC_ROOT_PUBKEY_EXPIRED = new Securty_RetCode(3,_SEC_RC_ROOT_PUBKEY_EXPIRED,"SEC_RC_ROOT_PUBKEY_EXPIRED");
    public static final int _SEC_RC_APP_PUBKEY_EXPIRED = -4;
    public static final Securty_RetCode SEC_RC_APP_PUBKEY_EXPIRED = new Securty_RetCode(4,_SEC_RC_APP_PUBKEY_EXPIRED,"SEC_RC_APP_PUBKEY_EXPIRED");
    public static final int _SEC_RC_INVALID_PARAM = -5;
    public static final Securty_RetCode SEC_RC_INVALID_PARAM = new Securty_RetCode(5,_SEC_RC_INVALID_PARAM,"SEC_RC_INVALID_PARAM");
    public static final int _SEC_RC_DECRYPT_FAILED = -6;
    public static final Securty_RetCode SEC_RC_DECRYPT_FAILED = new Securty_RetCode(6,_SEC_RC_DECRYPT_FAILED,"SEC_RC_DECRYPT_FAILED");
    public static final int _SEC_RC_SERVER_ERR = -999;
    public static final Securty_RetCode SEC_RC_SERVER_ERR = new Securty_RetCode(7,_SEC_RC_SERVER_ERR,"SEC_RC_SERVER_ERR");

    public static Securty_RetCode convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static Securty_RetCode convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private Securty_RetCode(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
