// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.1.1.2 by WSRD Tencent.
// Generated from `SecProxy.jce'
// **********************************************************************

package TRom;

public final class SecureReq extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "TRom.SecureReq";
    }

    public String fullClassName()
    {
        return "TRom.SecureReq";
    }

    public String sSessionId = "";

    public byte [] vGUID = null;

    public String sPackageName = "";

    public byte [] vRealReq = null;

    public boolean bZip = false;

    public String getSSessionId()
    {
        return sSessionId;
    }

    public void  setSSessionId(String sSessionId)
    {
        this.sSessionId = sSessionId;
    }

    public byte [] getVGUID()
    {
        return vGUID;
    }

    public void  setVGUID(byte [] vGUID)
    {
        this.vGUID = vGUID;
    }

    public String getSPackageName()
    {
        return sPackageName;
    }

    public void  setSPackageName(String sPackageName)
    {
        this.sPackageName = sPackageName;
    }

    public byte [] getVRealReq()
    {
        return vRealReq;
    }

    public void  setVRealReq(byte [] vRealReq)
    {
        this.vRealReq = vRealReq;
    }

    public boolean getBZip()
    {
        return bZip;
    }

    public void  setBZip(boolean bZip)
    {
        this.bZip = bZip;
    }

    public SecureReq()
    {
    }

    public SecureReq(String sSessionId, byte [] vGUID, String sPackageName, byte [] vRealReq, boolean bZip)
    {
        this.sSessionId = sSessionId;
        this.vGUID = vGUID;
        this.sPackageName = sPackageName;
        this.vRealReq = vRealReq;
        this.bZip = bZip;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        SecureReq t = (SecureReq) o;
        return (
            com.qq.taf.jce.JceUtil.equals(sSessionId, t.sSessionId) && 
            com.qq.taf.jce.JceUtil.equals(vGUID, t.vGUID) && 
            com.qq.taf.jce.JceUtil.equals(sPackageName, t.sPackageName) && 
            com.qq.taf.jce.JceUtil.equals(vRealReq, t.vRealReq) && 
            com.qq.taf.jce.JceUtil.equals(bZip, t.bZip) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(sSessionId, 1);
        _os.write(vGUID, 2);
        _os.write(sPackageName, 3);
        _os.write(vRealReq, 4);
        _os.write(bZip, 5);
    }

    static byte [] cache_vGUID;
    static byte [] cache_vRealReq;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.sSessionId =  _is.readString(1, true);
        if(null == cache_vGUID)
        {
            cache_vGUID = (byte[]) new byte[1];
            byte __var_1 = 0;
            ((byte[])cache_vGUID)[0] = __var_1;
        }
        this.vGUID = (byte []) _is.read(cache_vGUID, 2, true);
        this.sPackageName =  _is.readString(3, true);
        if(null == cache_vRealReq)
        {
            cache_vRealReq = (byte[]) new byte[1];
            byte __var_2 = 0;
            ((byte[])cache_vRealReq)[0] = __var_2;
        }
        this.vRealReq = (byte []) _is.read(cache_vRealReq, 4, true);
        this.bZip = (boolean) _is.read(bZip, 5, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(sSessionId, "sSessionId");
        _ds.display(vGUID, "vGUID");
        _ds.display(sPackageName, "sPackageName");
        _ds.display(vRealReq, "vRealReq");
        _ds.display(bZip, "bZip");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(sSessionId, true);
        _ds.displaySimple(vGUID, true);
        _ds.displaySimple(sPackageName, true);
        _ds.displaySimple(vRealReq, true);
        _ds.displaySimple(bZip, false);
    }

}

