// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.4 by WSRD Tencent.
// Generated from `/usr/local/app/taf/tafnode/data/Test.GetJceJavaServer/bin//doc/upload/20150813/Security.jce'
// **********************************************************************

package TRom;

public final class SessionInfoRsp extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "TRom.SessionInfoRsp";
    }

    public String fullClassName()
    {
        return "TRom.SessionInfoRsp";
    }

    public String sActiveKey = "";

    public String getSActiveKey()
    {
        return sActiveKey;
    }

    public void  setSActiveKey(String sActiveKey)
    {
        this.sActiveKey = sActiveKey;
    }

    public SessionInfoRsp()
    {
    }

    public SessionInfoRsp(String sActiveKey)
    {
        this.sActiveKey = sActiveKey;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        SessionInfoRsp t = (SessionInfoRsp) o;
        return (
            com.qq.taf.jce.JceUtil.equals(sActiveKey, t.sActiveKey) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != sActiveKey)
        {
            _os.write(sActiveKey, 1);
        }
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.sActiveKey =  _is.readString(1, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(sActiveKey, "sActiveKey");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(sActiveKey, false);
    }

}

