// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.4 by WSRD Tencent.
// Generated from `/usr/local/app/taf/tafnode/data/Test.GetJceJavaServer/bin//doc/upload/20150813/Security.jce'
// **********************************************************************

package TRom;

public final class SessionInfoReq extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "TRom.SessionInfoReq";
    }

    public String fullClassName()
    {
        return "TRom.SessionInfoReq";
    }

    public String sApp = "";

    public String sAppToken = "";

    public String sSessionId = "";

    public String sUserKey = "";

    public String getSApp()
    {
        return sApp;
    }

    public void  setSApp(String sApp)
    {
        this.sApp = sApp;
    }

    public String getSAppToken()
    {
        return sAppToken;
    }

    public void  setSAppToken(String sAppToken)
    {
        this.sAppToken = sAppToken;
    }

    public String getSSessionId()
    {
        return sSessionId;
    }

    public void  setSSessionId(String sSessionId)
    {
        this.sSessionId = sSessionId;
    }

    public String getSUserKey()
    {
        return sUserKey;
    }

    public void  setSUserKey(String sUserKey)
    {
        this.sUserKey = sUserKey;
    }

    public SessionInfoReq()
    {
    }

    public SessionInfoReq(String sApp, String sAppToken, String sSessionId, String sUserKey)
    {
        this.sApp = sApp;
        this.sAppToken = sAppToken;
        this.sSessionId = sSessionId;
        this.sUserKey = sUserKey;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        SessionInfoReq t = (SessionInfoReq) o;
        return (
            com.qq.taf.jce.JceUtil.equals(sApp, t.sApp) && 
            com.qq.taf.jce.JceUtil.equals(sAppToken, t.sAppToken) && 
            com.qq.taf.jce.JceUtil.equals(sSessionId, t.sSessionId) && 
            com.qq.taf.jce.JceUtil.equals(sUserKey, t.sUserKey) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(sApp, 1);
        _os.write(sAppToken, 2);
        _os.write(sSessionId, 3);
        _os.write(sUserKey, 4);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.sApp =  _is.readString(1, true);
        this.sAppToken =  _is.readString(2, true);
        this.sSessionId =  _is.readString(3, true);
        this.sUserKey =  _is.readString(4, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(sApp, "sApp");
        _ds.display(sAppToken, "sAppToken");
        _ds.display(sSessionId, "sSessionId");
        _ds.display(sUserKey, "sUserKey");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(sApp, true);
        _ds.displaySimple(sAppToken, true);
        _ds.displaySimple(sSessionId, true);
        _ds.displaySimple(sUserKey, false);
    }

}

