// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.4 by WSRD Tencent.
// Generated from `/usr/local/app/taf/tafnode/data/Test.GetJceJavaServer/bin//doc/upload/20150813/Security.jce'
// **********************************************************************

package TRom;

public final class UserEncryptKeyReq extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "TRom.UserEncryptKeyReq";
    }

    public String fullClassName()
    {
        return "TRom.UserEncryptKeyReq";
    }

    public String sApp = "";

    public String sAppToken = "";

    public String sUserId = "";

    public String getSApp()
    {
        return sApp;
    }

    public void  setSApp(String sApp)
    {
        this.sApp = sApp;
    }

    public String getSAppToken()
    {
        return sAppToken;
    }

    public void  setSAppToken(String sAppToken)
    {
        this.sAppToken = sAppToken;
    }

    public String getSUserId()
    {
        return sUserId;
    }

    public void  setSUserId(String sUserId)
    {
        this.sUserId = sUserId;
    }

    public UserEncryptKeyReq()
    {
    }

    public UserEncryptKeyReq(String sApp, String sAppToken, String sUserId)
    {
        this.sApp = sApp;
        this.sAppToken = sAppToken;
        this.sUserId = sUserId;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        UserEncryptKeyReq t = (UserEncryptKeyReq) o;
        return (
            com.qq.taf.jce.JceUtil.equals(sApp, t.sApp) && 
            com.qq.taf.jce.JceUtil.equals(sAppToken, t.sAppToken) && 
            com.qq.taf.jce.JceUtil.equals(sUserId, t.sUserId) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(sApp, 1);
        _os.write(sAppToken, 2);
        _os.write(sUserId, 3);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.sApp =  _is.readString(1, true);
        this.sAppToken =  _is.readString(2, true);
        this.sUserId =  _is.readString(3, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(sApp, "sApp");
        _ds.display(sAppToken, "sAppToken");
        _ds.display(sUserId, "sUserId");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(sApp, true);
        _ds.displaySimple(sAppToken, true);
        _ds.displaySimple(sUserId, false);
    }

}

