// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.4 by WSRD Tencent.
// Generated from `TRomComm.jce'
// **********************************************************************

package TRom;

public final class E_ROM_DEVICE_TYPE implements java.io.Serializable
{
    private static E_ROM_DEVICE_TYPE[] __values = new E_ROM_DEVICE_TYPE[2];
    private int __value;
    private String __T = new String();

    public static final int _ERDT_PHONE = 0;
    public static final E_ROM_DEVICE_TYPE ERDT_PHONE = new E_ROM_DEVICE_TYPE(0,_ERDT_PHONE,"ERDT_PHONE");
    public static final int _ERDT_WATCH = 1;
    public static final E_ROM_DEVICE_TYPE ERDT_WATCH = new E_ROM_DEVICE_TYPE(1,_ERDT_WATCH,"ERDT_WATCH");

    public static E_ROM_DEVICE_TYPE convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static E_ROM_DEVICE_TYPE convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private E_ROM_DEVICE_TYPE(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
