// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.1.1.2 by WSRD Tencent.
// Generated from `LoginQ.jce'
// **********************************************************************

package TRom;

public final class EAPNTYPE implements java.io.Serializable
{
    private static EAPNTYPE[] __values = new EAPNTYPE[9];
    private int __value;
    private String __T = new String();

    public static final int _APN_UNKNOWN = 0;
    public static final EAPNTYPE APN_UNKNOWN = new EAPNTYPE(0,_APN_UNKNOWN,"APN_UNKNOWN");
    public static final int _APN_CMWAP = 1;
    public static final EAPNTYPE APN_CMWAP = new EAPNTYPE(1,_APN_CMWAP,"APN_CMWAP");
    public static final int _APN_CMNET = 2;
    public static final EAPNTYPE APN_CMNET = new EAPNTYPE(2,_APN_CMNET,"APN_CMNET");
    public static final int _APN_UNWAP = 3;
    public static final EAPNTYPE APN_UNWAP = new EAPNTYPE(3,_APN_UNWAP,"APN_UNWAP");
    public static final int _APN_UNNET = 4;
    public static final EAPNTYPE APN_UNNET = new EAPNTYPE(4,_APN_UNNET,"APN_UNNET");
    public static final int _APN_CTWAP = 5;
    public static final EAPNTYPE APN_CTWAP = new EAPNTYPE(5,_APN_CTWAP,"APN_CTWAP");
    public static final int _APN_CTNET = 6;
    public static final EAPNTYPE APN_CTNET = new EAPNTYPE(6,_APN_CTNET,"APN_CTNET");
    public static final int _APN_3GWAP = 7;
    public static final EAPNTYPE APN_3GWAP = new EAPNTYPE(7,_APN_3GWAP,"APN_3GWAP");
    public static final int _APN_3GNET = 8;
    public static final EAPNTYPE APN_3GNET = new EAPNTYPE(8,_APN_3GNET,"APN_3GNET");

    public static EAPNTYPE convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static EAPNTYPE convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private EAPNTYPE(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
