// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.1 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/sukeyli/LoginQ.jce'
// **********************************************************************

package TRom;

public final class IPListReq extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "TRom.IPListReq";
    }

    public String fullClassName()
    {
        return "TRom.IPListReq";
    }

    public byte [] vGUID = null;

    public java.util.ArrayList<Integer> vIPType = null;

    public int eApnType = 0;

    public int eNetType = 0;

    public boolean bAll = false;

    public byte [] getVGUID()
    {
        return vGUID;
    }

    public void  setVGUID(byte [] vGUID)
    {
        this.vGUID = vGUID;
    }

    public java.util.ArrayList<Integer> getVIPType()
    {
        return vIPType;
    }

    public void  setVIPType(java.util.ArrayList<Integer> vIPType)
    {
        this.vIPType = vIPType;
    }

    public int getEApnType()
    {
        return eApnType;
    }

    public void  setEApnType(int eApnType)
    {
        this.eApnType = eApnType;
    }

    public int getENetType()
    {
        return eNetType;
    }

    public void  setENetType(int eNetType)
    {
        this.eNetType = eNetType;
    }

    public boolean getBAll()
    {
        return bAll;
    }

    public void  setBAll(boolean bAll)
    {
        this.bAll = bAll;
    }

    public IPListReq()
    {
    }

    public IPListReq(byte [] vGUID, java.util.ArrayList<Integer> vIPType, int eApnType, int eNetType, boolean bAll)
    {
        this.vGUID = vGUID;
        this.vIPType = vIPType;
        this.eApnType = eApnType;
        this.eNetType = eNetType;
        this.bAll = bAll;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        IPListReq t = (IPListReq) o;
        return (
            com.qq.taf.jce.JceUtil.equals(vGUID, t.vGUID) && 
            com.qq.taf.jce.JceUtil.equals(vIPType, t.vIPType) && 
            com.qq.taf.jce.JceUtil.equals(eApnType, t.eApnType) && 
            com.qq.taf.jce.JceUtil.equals(eNetType, t.eNetType) && 
            com.qq.taf.jce.JceUtil.equals(bAll, t.bAll) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != vGUID)
        {
            _os.write(vGUID, 0);
        }
        if (null != vIPType)
        {
            _os.write(vIPType, 1);
        }
        _os.write(eApnType, 2);
        _os.write(eNetType, 3);
        _os.write(bAll, 4);
    }

    static byte [] cache_vGUID;
    static java.util.ArrayList<Integer> cache_vIPType;
    static int cache_eApnType;
    static int cache_eNetType;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        if(null == cache_vGUID)
        {
            cache_vGUID = (byte[]) new byte[1];
            byte __var_3 = 0;
            ((byte[])cache_vGUID)[0] = __var_3;
        }
        this.vGUID = (byte []) _is.read(cache_vGUID, 0, false);
        if(null == cache_vIPType)
        {
            cache_vIPType = new java.util.ArrayList<Integer>();
            Integer __var_4 = 0;
            ((java.util.ArrayList<Integer>)cache_vIPType).add(__var_4);
        }
        this.vIPType = (java.util.ArrayList<Integer>) _is.read(cache_vIPType, 1, false);
        this.eApnType = (int) _is.read(eApnType, 2, false);
        this.eNetType = (int) _is.read(eNetType, 3, false);
        this.bAll = (boolean) _is.read(bAll, 4, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(vGUID, "vGUID");
        _ds.display(vIPType, "vIPType");
        _ds.display(eApnType, "eApnType");
        _ds.display(eNetType, "eNetType");
        _ds.display(bAll, "bAll");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(vGUID, true);
        _ds.displaySimple(vIPType, true);
        _ds.displaySimple(eApnType, true);
        _ds.displaySimple(eNetType, true);
        _ds.displaySimple(bAll, false);
    }

}

