// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.4 by WSRD Tencent.
// Generated from `TRomComm.jce'
// **********************************************************************

package TRom;

public final class RomBaseInfo extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "TRom.RomBaseInfo";
    }

    public String fullClassName()
    {
        return "TRom.RomBaseInfo";
    }

    public byte [] vGUID = null;

    public String sQUA = "";

    public String sIMEI = "";

    public String sQIMEI = "";

    public String sLC = "";

    public long iRomId = 0;

    public String sPackName = "";

    public int eExtDataType = TRom.E_ROM_DEVICE_TYPE.ERDT_PHONE.value();

    public java.util.Map<String, String> mExtData = null;

    public byte [] getVGUID()
    {
        return vGUID;
    }

    public void  setVGUID(byte [] vGUID)
    {
        this.vGUID = vGUID;
    }

    public String getSQUA()
    {
        return sQUA;
    }

    public void  setSQUA(String sQUA)
    {
        this.sQUA = sQUA;
    }

    public String getSIMEI()
    {
        return sIMEI;
    }

    public void  setSIMEI(String sIMEI)
    {
        this.sIMEI = sIMEI;
    }

    public String getSQIMEI()
    {
        return sQIMEI;
    }

    public void  setSQIMEI(String sQIMEI)
    {
        this.sQIMEI = sQIMEI;
    }

    public String getSLC()
    {
        return sLC;
    }

    public void  setSLC(String sLC)
    {
        this.sLC = sLC;
    }

    public long getIRomId()
    {
        return iRomId;
    }

    public void  setIRomId(long iRomId)
    {
        this.iRomId = iRomId;
    }

    public String getSPackName()
    {
        return sPackName;
    }

    public void  setSPackName(String sPackName)
    {
        this.sPackName = sPackName;
    }

    public int getEExtDataType()
    {
        return eExtDataType;
    }

    public void  setEExtDataType(int eExtDataType)
    {
        this.eExtDataType = eExtDataType;
    }

    public java.util.Map<String, String> getMExtData()
    {
        return mExtData;
    }

    public void  setMExtData(java.util.Map<String, String> mExtData)
    {
        this.mExtData = mExtData;
    }

    public RomBaseInfo()
    {
    }

    public RomBaseInfo(byte [] vGUID, String sQUA, String sIMEI, String sQIMEI, String sLC, long iRomId, String sPackName, int eExtDataType, java.util.Map<String, String> mExtData)
    {
        this.vGUID = vGUID;
        this.sQUA = sQUA;
        this.sIMEI = sIMEI;
        this.sQIMEI = sQIMEI;
        this.sLC = sLC;
        this.iRomId = iRomId;
        this.sPackName = sPackName;
        this.eExtDataType = eExtDataType;
        this.mExtData = mExtData;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        RomBaseInfo t = (RomBaseInfo) o;
        return (
            com.qq.taf.jce.JceUtil.equals(vGUID, t.vGUID) && 
            com.qq.taf.jce.JceUtil.equals(sQUA, t.sQUA) && 
            com.qq.taf.jce.JceUtil.equals(sIMEI, t.sIMEI) && 
            com.qq.taf.jce.JceUtil.equals(sQIMEI, t.sQIMEI) && 
            com.qq.taf.jce.JceUtil.equals(sLC, t.sLC) && 
            com.qq.taf.jce.JceUtil.equals(iRomId, t.iRomId) && 
            com.qq.taf.jce.JceUtil.equals(sPackName, t.sPackName) && 
            com.qq.taf.jce.JceUtil.equals(eExtDataType, t.eExtDataType) && 
            com.qq.taf.jce.JceUtil.equals(mExtData, t.mExtData) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(vGUID, 0);
        _os.write(sQUA, 1);
        if (null != sIMEI)
        {
            _os.write(sIMEI, 2);
        }
        if (null != sQIMEI)
        {
            _os.write(sQIMEI, 3);
        }
        if (null != sLC)
        {
            _os.write(sLC, 4);
        }
        _os.write(iRomId, 5);
        if (null != sPackName)
        {
            _os.write(sPackName, 6);
        }
        _os.write(eExtDataType, 7);
        if (null != mExtData)
        {
            _os.write(mExtData, 8);
        }
    }

    static byte [] cache_vGUID;
    static int cache_eExtDataType;
    static java.util.Map<String, String> cache_mExtData;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        if(null == cache_vGUID)
        {
            cache_vGUID = (byte[]) new byte[1];
            byte __var_1 = 0;
            ((byte[])cache_vGUID)[0] = __var_1;
        }
        this.vGUID = (byte []) _is.read(cache_vGUID, 0, true);
        this.sQUA =  _is.readString(1, true);
        this.sIMEI =  _is.readString(2, false);
        this.sQIMEI =  _is.readString(3, false);
        this.sLC =  _is.readString(4, false);
        this.iRomId = (long) _is.read(iRomId, 5, false);
        this.sPackName =  _is.readString(6, false);
        this.eExtDataType = (int) _is.read(eExtDataType, 7, false);
        if(null == cache_mExtData)
        {
            cache_mExtData = new java.util.HashMap<String, String>();
            String __var_2 = "";
            String __var_3 = "";
            cache_mExtData.put(__var_2, __var_3);
        }
        this.mExtData = (java.util.Map<String, String>) _is.read(cache_mExtData, 8, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(vGUID, "vGUID");
        _ds.display(sQUA, "sQUA");
        _ds.display(sIMEI, "sIMEI");
        _ds.display(sQIMEI, "sQIMEI");
        _ds.display(sLC, "sLC");
        _ds.display(iRomId, "iRomId");
        _ds.display(sPackName, "sPackName");
        _ds.display(eExtDataType, "eExtDataType");
        _ds.display(mExtData, "mExtData");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(vGUID, true);
        _ds.displaySimple(sQUA, true);
        _ds.displaySimple(sIMEI, true);
        _ds.displaySimple(sQIMEI, true);
        _ds.displaySimple(sLC, true);
        _ds.displaySimple(iRomId, true);
        _ds.displaySimple(sPackName, true);
        _ds.displaySimple(eExtDataType, true);
        _ds.displaySimple(mExtData, false);
    }

}

