// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.1.1.2 by WSRD Tencent.
// Generated from `SecProxy.jce'
// **********************************************************************

package TRom;

public final class SECPROXY_RETCODE implements java.io.Serializable
{
    private static SECPROXY_RETCODE[] __values = new SECPROXY_RETCODE[10];
    private int __value;
    private String __T = new String();

    public static final int _SP_RC_OK = 0;
    public static final SECPROXY_RETCODE SP_RC_OK = new SECPROXY_RETCODE(0,_SP_RC_OK,"SP_RC_OK");
    public static final int _SP_RC_DECRYPT_FAILED = -1;
    public static final SECPROXY_RETCODE SP_RC_DECRYPT_FAILED = new SECPROXY_RETCODE(1,_SP_RC_DECRYPT_FAILED,"SP_RC_DECRYPT_FAILED");
    public static final int _SP_RC_INVALID_SERVANT = -2;
    public static final SECPROXY_RETCODE SP_RC_INVALID_SERVANT = new SECPROXY_RETCODE(2,_SP_RC_INVALID_SERVANT,"SP_RC_INVALID_SERVANT");
    public static final int _SP_RC_UNREGIST_PACKAGE = -3;
    public static final SECPROXY_RETCODE SP_RC_UNREGIST_PACKAGE = new SECPROXY_RETCODE(3,_SP_RC_UNREGIST_PACKAGE,"SP_RC_UNREGIST_PACKAGE");
    public static final int _SP_RC_SESSION_PARAM_ERROR = -4;
    public static final SECPROXY_RETCODE SP_RC_SESSION_PARAM_ERROR = new SECPROXY_RETCODE(4,_SP_RC_SESSION_PARAM_ERROR,"SP_RC_SESSION_PARAM_ERROR");
    public static final int _SP_RC_SESSION_OUTDATE = -5;
    public static final SECPROXY_RETCODE SP_RC_SESSION_OUTDATE = new SECPROXY_RETCODE(5,_SP_RC_SESSION_OUTDATE,"SP_RC_SESSION_OUTDATE");
    public static final int _SP_RC_ZIP_FAILED = -6;
    public static final SECPROXY_RETCODE SP_RC_ZIP_FAILED = new SECPROXY_RETCODE(6,_SP_RC_ZIP_FAILED,"SP_RC_ZIP_FAILED");
    public static final int _SP_RC_INVALID_GUID = -7;
    public static final SECPROXY_RETCODE SP_RC_INVALID_GUID = new SECPROXY_RETCODE(7,_SP_RC_INVALID_GUID,"SP_RC_INVALID_GUID");
    public static final int _SP_BUS_SERVER_FAILED = -8;
    public static final SECPROXY_RETCODE SP_BUS_SERVER_FAILED = new SECPROXY_RETCODE(8,_SP_BUS_SERVER_FAILED,"SP_BUS_SERVER_FAILED");
    public static final int _SP_RC_SERVER_ERR = -999;
    public static final SECPROXY_RETCODE SP_RC_SERVER_ERR = new SECPROXY_RETCODE(9,_SP_RC_SERVER_ERR,"SP_RC_SERVER_ERR");

    public static SECPROXY_RETCODE convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static SECPROXY_RETCODE convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private SECPROXY_RETCODE(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
