// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.1.1.2 by WSRD Tencent.
// Generated from `SecProxy.jce'
// **********************************************************************

package TRom;

public final class SecureRsp extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "TRom.SecureRsp";
    }

    public String fullClassName()
    {
        return "TRom.SecureRsp";
    }

    public int iRet = 0;

    public String sPackageName = "";

    public byte [] vRealRsp = null;

    public boolean bZip = false;

    public int getIRet()
    {
        return iRet;
    }

    public void  setIRet(int iRet)
    {
        this.iRet = iRet;
    }

    public String getSPackageName()
    {
        return sPackageName;
    }

    public void  setSPackageName(String sPackageName)
    {
        this.sPackageName = sPackageName;
    }

    public byte [] getVRealRsp()
    {
        return vRealRsp;
    }

    public void  setVRealRsp(byte [] vRealRsp)
    {
        this.vRealRsp = vRealRsp;
    }

    public boolean getBZip()
    {
        return bZip;
    }

    public void  setBZip(boolean bZip)
    {
        this.bZip = bZip;
    }

    public SecureRsp()
    {
    }

    public SecureRsp(int iRet, String sPackageName, byte [] vRealRsp, boolean bZip)
    {
        this.iRet = iRet;
        this.sPackageName = sPackageName;
        this.vRealRsp = vRealRsp;
        this.bZip = bZip;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        SecureRsp t = (SecureRsp) o;
        return (
            com.qq.taf.jce.JceUtil.equals(iRet, t.iRet) && 
            com.qq.taf.jce.JceUtil.equals(sPackageName, t.sPackageName) && 
            com.qq.taf.jce.JceUtil.equals(vRealRsp, t.vRealRsp) && 
            com.qq.taf.jce.JceUtil.equals(bZip, t.bZip) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(iRet, 1);
        _os.write(sPackageName, 2);
        if (null != vRealRsp)
        {
            _os.write(vRealRsp, 3);
        }
        _os.write(bZip, 4);
    }

    static byte [] cache_vRealRsp;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.iRet = (int) _is.read(iRet, 1, false);
        this.sPackageName =  _is.readString(2, true);
        if(null == cache_vRealRsp)
        {
            cache_vRealRsp = (byte[]) new byte[1];
            byte __var_3 = 0;
            ((byte[])cache_vRealRsp)[0] = __var_3;
        }
        this.vRealRsp = (byte []) _is.read(cache_vRealRsp, 3, false);
        this.bZip = (boolean) _is.read(bZip, 4, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(iRet, "iRet");
        _ds.display(sPackageName, "sPackageName");
        _ds.display(vRealRsp, "vRealRsp");
        _ds.display(bZip, "bZip");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(iRet, true);
        _ds.displaySimple(sPackageName, true);
        _ds.displaySimple(vRealRsp, true);
        _ds.displaySimple(bZip, false);
    }

}

