// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.4 by WSRD Tencent.
// Generated from `LogReport.jce'
// **********************************************************************

package TRom.log;

public final class ECheckTicketRetCode implements java.io.Serializable
{
    private static ECheckTicketRetCode[] __values = new ECheckTicketRetCode[7];
    private int __value;
    private String __T = new String();

    public static final int _E_TICKET_SUCC = 0;
    public static final ECheckTicketRetCode E_TICKET_SUCC = new ECheckTicketRetCode(0,_E_TICKET_SUCC,"E_TICKET_SUCC");
    public static final int _E_TICKET_EMPTY = -1;
    public static final ECheckTicketRetCode E_TICKET_EMPTY = new ECheckTicketRetCode(1,_E_TICKET_EMPTY,"E_TICKET_EMPTY");
    public static final int _E_TICKET_DECRYPT_ERR = -2;
    public static final ECheckTicketRetCode E_TICKET_DECRYPT_ERR = new ECheckTicketRetCode(2,_E_TICKET_DECRYPT_ERR,"E_TICKET_DECRYPT_ERR");
    public static final int _E_TICKET_FORMAT_ERR = -3;
    public static final ECheckTicketRetCode E_TICKET_FORMAT_ERR = new ECheckTicketRetCode(3,_E_TICKET_FORMAT_ERR,"E_TICKET_FORMAT_ERR");
    public static final int _E_TICKET_GUID_ERR = -4;
    public static final ECheckTicketRetCode E_TICKET_GUID_ERR = new ECheckTicketRetCode(4,_E_TICKET_GUID_ERR,"E_TICKET_GUID_ERR");
    public static final int _E_TICKET_EXPIRE = -5;
    public static final ECheckTicketRetCode E_TICKET_EXPIRE = new ECheckTicketRetCode(5,_E_TICKET_EXPIRE,"E_TICKET_EXPIRE");
    public static final int _E_TICKET_FREQ_LIMITED = -6;
    public static final ECheckTicketRetCode E_TICKET_FREQ_LIMITED = new ECheckTicketRetCode(6,_E_TICKET_FREQ_LIMITED,"E_TICKET_FREQ_LIMITED");

    public static ECheckTicketRetCode convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static ECheckTicketRetCode convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private ECheckTicketRetCode(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
