// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.4 by WSRD Tencent.
// Generated from `LogReport.jce'
// **********************************************************************

package TRom.log;

public final class ELogReportRetCode implements java.io.Serializable
{
    private static ELogReportRetCode[] __values = new ELogReportRetCode[7];
    private int __value;
    private String __T = new String();

    public static final int _E_REPORT_SUCC = 0;
    public static final ELogReportRetCode E_REPORT_SUCC = new ELogReportRetCode(0,_E_REPORT_SUCC,"E_REPORT_SUCC");
    public static final int _E_REPORT_INVALID_BUSS = -1;
    public static final ELogReportRetCode E_REPORT_INVALID_BUSS = new ELogReportRetCode(1,_E_REPORT_INVALID_BUSS,"E_REPORT_INVALID_BUSS");
    public static final int _E_REPORT_INVALID_MODULE = -2;
    public static final ELogReportRetCode E_REPORT_INVALID_MODULE = new ELogReportRetCode(2,_E_REPORT_INVALID_MODULE,"E_REPORT_INVALID_MODULE");
    public static final int _E_REPORT_INVALID_PARAM = -3;
    public static final ELogReportRetCode E_REPORT_INVALID_PARAM = new ELogReportRetCode(3,_E_REPORT_INVALID_PARAM,"E_REPORT_INVALID_PARAM");
    public static final int _E_REPORT_INVALID_CALL = -4;
    public static final ELogReportRetCode E_REPORT_INVALID_CALL = new ELogReportRetCode(4,_E_REPORT_INVALID_CALL,"E_REPORT_INVALID_CALL");
    public static final int _E_REPORT_INVALID_TICKET = -5;
    public static final ELogReportRetCode E_REPORT_INVALID_TICKET = new ELogReportRetCode(5,_E_REPORT_INVALID_TICKET,"E_REPORT_INVALID_TICKET");
    public static final int _E_REPORT_SVR_ERR = -99;
    public static final ELogReportRetCode E_REPORT_SVR_ERR = new ELogReportRetCode(6,_E_REPORT_SVR_ERR,"E_REPORT_SVR_ERR");

    public static ELogReportRetCode convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static ELogReportRetCode convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private ELogReportRetCode(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
