// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.4 by WSRD Tencent.
// Generated from `LogReport.jce'
// **********************************************************************

package TRom.log;

public final class ReportLogReq extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "TRom.ReportLogReq";
    }

    public String fullClassName()
    {
        return "TRom.ReportLogReq";
    }

    public TRom.RomBaseInfo stRomBaseInfo = null;

    public String sBussName = "default";

    public int iErrCode = 0;

    public String sErrMsg = "";

    public byte [] vData = null;

    public TRom.RomBaseInfo getStRomBaseInfo()
    {
        return stRomBaseInfo;
    }

    public void  setStRomBaseInfo(TRom.RomBaseInfo stRomBaseInfo)
    {
        this.stRomBaseInfo = stRomBaseInfo;
    }

    public String getSBussName()
    {
        return sBussName;
    }

    public void  setSBussName(String sBussName)
    {
        this.sBussName = sBussName;
    }

    public int getIErrCode()
    {
        return iErrCode;
    }

    public void  setIErrCode(int iErrCode)
    {
        this.iErrCode = iErrCode;
    }

    public String getSErrMsg()
    {
        return sErrMsg;
    }

    public void  setSErrMsg(String sErrMsg)
    {
        this.sErrMsg = sErrMsg;
    }

    public byte [] getVData()
    {
        return vData;
    }

    public void  setVData(byte [] vData)
    {
        this.vData = vData;
    }

    public ReportLogReq()
    {
    }

    public ReportLogReq(TRom.RomBaseInfo stRomBaseInfo, String sBussName, int iErrCode, String sErrMsg, byte [] vData)
    {
        this.stRomBaseInfo = stRomBaseInfo;
        this.sBussName = sBussName;
        this.iErrCode = iErrCode;
        this.sErrMsg = sErrMsg;
        this.vData = vData;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ReportLogReq t = (ReportLogReq) o;
        return (
            com.qq.taf.jce.JceUtil.equals(stRomBaseInfo, t.stRomBaseInfo) && 
            com.qq.taf.jce.JceUtil.equals(sBussName, t.sBussName) && 
            com.qq.taf.jce.JceUtil.equals(iErrCode, t.iErrCode) && 
            com.qq.taf.jce.JceUtil.equals(sErrMsg, t.sErrMsg) && 
            com.qq.taf.jce.JceUtil.equals(vData, t.vData) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != stRomBaseInfo)
        {
            _os.write(stRomBaseInfo, 0);
        }
        if (null != sBussName)
        {
            _os.write(sBussName, 1);
        }
        _os.write(iErrCode, 2);
        if (null != sErrMsg)
        {
            _os.write(sErrMsg, 3);
        }
        if (null != vData)
        {
            _os.write(vData, 4);
        }
    }

    static TRom.RomBaseInfo cache_stRomBaseInfo;
    static byte [] cache_vData;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        if(null == cache_stRomBaseInfo)
        {
            cache_stRomBaseInfo = new TRom.RomBaseInfo();
        }
        this.stRomBaseInfo = (TRom.RomBaseInfo) _is.read(cache_stRomBaseInfo, 0, false);
        this.sBussName =  _is.readString(1, false);
        this.iErrCode = (int) _is.read(iErrCode, 2, false);
        this.sErrMsg =  _is.readString(3, false);
        if(null == cache_vData)
        {
            cache_vData = (byte[]) new byte[1];
            byte __var_1 = 0;
            ((byte[])cache_vData)[0] = __var_1;
        }
        this.vData = (byte []) _is.read(cache_vData, 4, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(stRomBaseInfo, "stRomBaseInfo");
        _ds.display(sBussName, "sBussName");
        _ds.display(iErrCode, "iErrCode");
        _ds.display(sErrMsg, "sErrMsg");
        _ds.display(vData, "vData");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(stRomBaseInfo, true);
        _ds.displaySimple(sBussName, true);
        _ds.displaySimple(iErrCode, true);
        _ds.displaySimple(sErrMsg, true);
        _ds.displaySimple(vData, false);
    }

}

